- name: Marius van Niekerk
  email: marius.v.niekerk@gmail.com
  num_commits: 0
  first_commit: 2018-10-13 11:39:05
- name: Igor T. Ghisi
  email: igor.ghisi@gmail.com
  num_commits: 4
  github: igortg
  first_commit: 2018-02-26 18:09:46
- name: Aaron Meurer
  email: asmeurer@gmail.com
  num_commits: 35
  first_commit: 2017-06-23 14:44:39
  github: asmeurer
- name: Christopher J. Wright
  email: cjwright4242gh@gmail.com
  num_commits: 143
  first_commit: 2017-07-25 20:41:13
  alternate_emails:
  - cjwright4242@gmail.com
  aliases:
  - christopher
  - Christopher J. 'CJ' Wright
- name: Dougal J. Sutherland
  email: dougal@gmail.com
  num_commits: 1
  github: dougalsutherland
  first_commit: 2018-08-11 13:07:29
- name: Anthony Scopatz
  email: scopatz@gmail.com
  num_commits: 345
  first_commit: 2017-05-16 14:52:07
- name: Christoph Deil
  email: Deil.Christoph@gmail.com
  github: cdeil
  num_commits: 1
  first_commit: 2018-10-17 16:35:00
- name: ERGS
  email: scopatz@cec.sc.edu
  is_org: true
  github: ergs
  num_commits: 0
  first_commit: 2019-01-18 16:18:54.253827
- name: Michael Sarahan
  aliases:
  - Mike Sarahan
  email: msarahan@gmail.com
  num_commits: 6
  first_commit: 2019-05-14 21:01:12
  github: msarahan
- name: Baptiste Mouginot
  email: mouginot.baptiste@gmail.com
  github: bam241
  num_commits: 1
  first_commit: 2019-07-01 11:49:22
- name: Thomas Kluyver
  email: thomas@kluyver.me.uk
  num_commits: 5
  first_commit: 2019-10-24 08:16:16
  github: takluyver
- name: Melissa Weber Mendonça
  email: melissawm@gmail.com
  num_commits: 1
  first_commit: 2020-06-23 20:50:27
  github: melissawm
- name: a
  email: a
  num_commits: 8
  first_commit: 2020-08-09 20:16:03.203561
- name: Bas Nijholt
  email: basnijholt@gmail.com
  num_commits: 1
  first_commit: 2020-04-16 04:18:12
  github: basnijholt
- name: Julian Rüth
  email: julian.rueth@fsfe.org
  num_commits: 7
  first_commit: 2020-08-19 07:34:05
  github: saraedum
- name: Hadrien Mary
  email: hadrien.mary@gmail.com
  num_commits: 14
  first_commit: 2020-08-22 10:03:21
  github: hadim
- name: anki-code
  email: anki-code@users.noreply.github.com
  num_commits: 7
  first_commit: 2020-10-14 14:50:25
- name: Rob Koch
  email: rkoch177@gmail.com
  num_commits: 12
  first_commit: 2021-03-29 19:39:58
  github: rjkoch
- name: Robert J Koch
  email: 52714660+rjkoch@users.noreply.github.com
  num_commits: 0
  first_commit: 2021-05-04 08:37:59
  github: rjkoch
- name: Simon Billinge
  email: simon.billinge@gmail.com
  num_commits: 1
  first_commit: 2022-06-17 15:17:47
  github: sbillinge
